version: "2"
run:
  go: "1.20"
linters:
  enable:
    - gocritic
    - misspell
    - nolintlint
    - revive
    - unconvert
  settings:
    gocritic:
      disabled-checks:
        - hugeParam
      enabled-tags:
        - diagnostic
        - performance
    misspell:
      locale: US
    nolintlint:
      require-explanation: true
      require-specific: true
    revive:
      rules:
        - name: blank-imports
        - name: exported
          arguments:
            - checkPrivateReceivers
        - name: error-return
        - name: error-strings
        - name: increment-decrement
        - name: indent-error-flow
        - name: receiver-naming
        - name: range
        - name: unexported-return
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - gocritic
        path: _test\.go
      - linters:
          - errcheck
          - revive
          - gocritic
        path: examples/
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/kirinyoku/enkanetwork-go
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
